// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Vjap3AEumJnE6p6AGAG8o_g1-WNO7N8',
    appId: '1:720395923244:web:ecf722dfec310783efc689',
    messagingSenderId: '720395923244',
    projectId: 'api-document-816b2',
    authDomain: 'api-document-816b2.firebaseapp.com',
    databaseURL: 'https://api-document-816b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'api-document-816b2.appspot.com',
    measurementId: 'G-PN4DCQC14R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwL8O9R8Kcj3p6Ggaf7W00wbpNheiSlOc',
    appId: '1:720395923244:android:37cc0bd95bf7f0ebefc689',
    messagingSenderId: '720395923244',
    projectId: 'api-document-816b2',
    databaseURL: 'https://api-document-816b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'api-document-816b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5r_LGR3vpnzx6SZZNoixxfxJb9te_BWw',
    appId: '1:720395923244:ios:12edfffaafc9ba60efc689',
    messagingSenderId: '720395923244',
    projectId: 'api-document-816b2',
    databaseURL: 'https://api-document-816b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'api-document-816b2.appspot.com',
    iosBundleId: 'com.example.apiDocument',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5r_LGR3vpnzx6SZZNoixxfxJb9te_BWw',
    appId: '1:720395923244:ios:07b9e9d0f060ba74efc689',
    messagingSenderId: '720395923244',
    projectId: 'api-document-816b2',
    databaseURL: 'https://api-document-816b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'api-document-816b2.appspot.com',
    iosBundleId: 'com.example.apiDocument.RunnerTests',
  );
}
